---
- name: Retrieve OS and Distribution Details
  hosts: localhost  # Replace with your VM hostname or IP address
  gather_facts: true

  tasks:
    - name: Fetch host facts
      setup:

    - name: Display OS and Distribution details
      debug:
        msg: "Operating System: {{ ansible_distribution }} {{ ansible_distribution_version }}"
